### ISSUE TITLE
Support Assembly?

### ISSUE THREAD

**Issue by AlongWY** [Lord-Turmoil/CodePaste#8]
Can we support Assembly Language?

**Comment by Lord-Turmoil** [comment]
I'm not sure what assembly language you're using. However, PrismJS has support for NASM, which works fine with most assembly languages.

> For assembly language support of PrismJS, you can refer to this issue: [syntax highlighting for assembly](https://github.com/PrismJS/prism/issues/482).

Thanks for reaching out, hope it is what you want. If not, you can reopen this issue. 😉

**Comment by AlongWY** [comment]
Thank a lot!
